apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nwej2h8sq-go
  janus-idp.io/tekton: nwej2h8sq-go
  backstage.io/kubernetes-id: nwej2h8sq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nwej2h8sq-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
