apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nwej2h8sq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nwej2h8sq-go 
  name: nwej2h8sq-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nwej2h8sq-go
    weight: 100 
