apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nwej2h8sq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nwej2h8sq-go 
  name: nwej2h8sq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nwej2h8sq-go 
