apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nwej2h8sq-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7f83a95ba2.cisn.p3.openshiftapps.com/rhtap/rhtap-qe:b50fd83bb6cf44e2979de4bdf42b2346420ceea4@sha256:b193133388fb5370333476cf7ee1dcd52527a2ddee434098661e392261ff95c3
          name: container-image
